### ISSUE TITLE
Error: spawn /usr/bin/node ENOENT when launching a process with child_process.spawn from app packaged with electron-packager

### ISSUE THREAD

**Issue by alintintesan** [electron/packager#1580] opened 2023-10-20 09:02 UTC
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.1.0
* **Electron Version:**
  * 24.8.4
* **Operating System:**
  * Ubuntu 22.04.2
* **Last Known Working Electron Packager version:**:
  * 

### Expected Behavior
The process should be launched successfully.

### Actual Behavior
The following error is being thrown: Error: spawn /usr/local/bin/node ENOENT

### To Reproduce
Package the app with:
packager({
    platform: 'linux',
    arch: 'x64',
    electronVersion: version,
    dir: './dist',
    out: './build/linux',
    name: 'UFT Developer',
    overwrite: true,
    prune: false,
    'appCopyright': "Copyright 2015 - 2023 Open Text."
});
Then after launching it, try launching a process programatically from the electron packaged app context like so:
child_process.spawn("/usr/bin/node", ["./leanft.js", "--port=5095", "--role=local"], { detached: true, stdio: "ignore", cwd: 
"pathToLeanftJs", windowsHide: true });

Finally, Error: spawn /usr/bin/node ENOENT is thrown.

### Additional Information
PATH env variable looks like this /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
Tried to launch with /usr/local/bin/node instead of /usr/bin/node but the result is the same (error is NOENT /usr/local/bin/node). Also reproduces on Mac 12+.
Added https://www.npmjs.com/package/fix-path logic but still doesn't work.

**Comment by erikian** [comment] 2023-10-26 12:23
What is the output of `file /usr/bin/node`? Maybe your Node binary is located somewhere else (you can check with `which node`).

**Comment by alintintesan** [comment] 2023-10-27 08:07
![image](https://github.com/electron/electron-packager/assets/33527312/8eeb3f98-3311-4269-90ee-04fe59d7fd17)

The same things happens if I try to launch it with /usr/local/bin/node, since the path points to this location, as mentioned in the additional information section.

**Comment by alintintesan** [comment] 2023-12-06 12:53
@erikian any updates?

**Comment by erikian** [comment] 2023-12-06 15:11
I couldn't reproduce the error, could you provide a repository with a minimal reproduction? Also, have you tried just `child_process.spawn("node")` (i.e. no absolute path)?

**Comment by erikian** [comment] 2024-01-10 21:01
I'm closing this issue for now since there's no repro — let me now if it's still a problem!

**Closed by erikian** 2024-01-10 21:01 UTC
Labels: bug :bug:, needs info
